transaction docs update
nimiq/developer-center pull request #77
Opened 2024-10-23 14:55 UTC by ines-toupeira

2024-11-14 18:22 UTC, ii-cruz requested changes

2024-11-14 18:22 UTC, ii-cruz commented on learn/protocol/transactions.md
> +A transaction must pass validity checks before being processed. Once the transaction is successfully validated, the boolean variable `valid` is set to `true`, confirming that the transaction has been
I think this is a bit confusing so perhaps let's not say anything here. The paragraph right before Transaction Structure refers to it needing to be validated and then refers to the mempool documentation for more info and later on doc we explain that we commit failed transactions and reject the ones that cannot be deducted their fee, seams complete enough.

2024-11-14 18:22 UTC, ii-cruz commented on learn/protocol/transactions.md
> +- **Staking-Related Transactions**: In staking-related transactions, the **sender** and **recipient** addresses can be the same, which is a specific feature of transactions interacting with the staki
This cannot happen as we discussed. Just making it so you see where it is.

2024-11-14 18:22 UTC, ii-cruz commented on learn/protocol/transactions.md
> +- **Incoming and Outgoing Transactions**: The network distinguishes between incoming and outgoing transactions. **Incoming transactions** are related to operations within the blockchain such as addin
As we discussed, this explanation needs some corrections. Marking it so you don't forget

2024-11-14 18:22 UTC, ii-cruz commented on learn/protocol/transactions.md
> +- **Transaction 3**: Alice tries to send another transaction but does not have enough NIM to cover even the fees. In this case, the transaction is deemed **invalid** and is not processed by the netwo
```suggestion
- **Transaction 3**: Alice tries to send another transaction but does not have enough NIM to cover the fee. In this case, the transaction is deemed **invalid** and is not processed by the network. Neither the value nor the fees are deducted
```

2024-11-14 18:22 UTC, ii-cruz commented on learn/protocol/transactions.md
> +Finality is periodically reinforced through the Tendermint protocol, which ensures that blocks and the transactions within them cannot be reversed with once they are finalized by a macro block. For m
```suggestion
Finality is periodically reinforced through the Tendermint protocol, which ensures that blocks and the transactions within them cannot be reversed once they are finalized by a macro block. For more details on how finality is achieved through the block structure, please refer to the [block format](block-format.md) documentation.
```

2024-11-14 18:22 UTC, ii-cruz commented on learn/protocol/transactions.md
> +Finality is periodically reinforced through the Tendermint protocol, which ensures that blocks and the transactions within them cannot be reversed with once they are finalized by a macro block. For m
Do you mean block structure here? It seems like the finality is achieved by the structure of a macro block and I guess what you mean is that the finality is periodically achieved by the consensus algorithm we use.

2024-11-14 18:22 UTC, ii-cruz commented on learn/protocol/transactions.md
> +In addition to user-initiated transactions, Nimiq also processes **inherents**—system-generated operations that modify the blockchain’s state without requiring a transaction from a user. These are us
```suggestion
In addition to user-initiated transactions, Nimiq also processes **inherents**—system-generated operations that modify the blockchain’s state without requiring a transaction from a user. These are used for tasks like distributing rewards and enforcing punishments, ensuring network stability.
```

2024-11-14 18:22 UTC, ii-cruz commented on learn/protocol/transactions.md
> +- **Finalize Batch**: Triggered at the end of each batch of micro blocks, marking the completion of a micro block batch
```suggestion
- **Finalize Batch**: Triggered at the end of each batch of micro blocks, marking its completion
```

2024-11-16 20:32 UTC, ii-cruz commented on learn/protocol/transactions.md
> +- **Invalid Sender**: The sender is not valid for the recipient. Some transactions, particularly staking-related ones, have special restrictions on the sender field. For example, self-transactions in
The sender and recipient cannot be the same

2024-11-16 20:32 UTC, ii-cruz commented on learn/protocol/transactions.md
> +- **Sender Equals Recipient**: The sender and recipient of the transaction are the same, which is not allowed unless under specific conditions (e.g., in staking-related transactions)
The sender and recipient cannot be the same. The staking contract is no exception

2024-11-16 22:52 UTC, ii-cruz approved these changes
LGTM :)

2024-11-18 16:17 UTC, paberr approved these changes

2024-11-18 22:21 UTC, merged