New Validators section
nimiq/developer-center pull request #89
Opened 2024-12-13 18:38 UTC by ines-toupeira

- Created the Validators section in the Developer Center to consolidate resources for stakers and pools
- Integrated the newly updated VTS documentation into the section
- Updated navigation and links to ensure proper access to all resources

2025-01-07 04:21 UTC, onmax requested changes
I did my review a few weeks back, but didn't submit it 🙃, so here it is.

2025-01-07 04:21 UTC, onmax commented on .vitepress/navigation.config.ts
> +        iconClasses: 'i-nimiq:icons-lg-three-hands-hexagon text-white/20 rotate-y-180 rotate-z-180',
Usually for validators we use `icons-lg-verified-filled` or `icons-lg-verified`

https://www.nimiq.com/developers/build/ui/design/icons?icon=nimiq%3Aicons-lg-verified-filled

2025-01-07 04:21 UTC, onmax commented on validators/index.md
> +  - label: FAQ
This section without title looks off.

Maybe title: `Any question?`
Maybe description: `Check out our most frequent questions`

2025-01-07 04:21 UTC, onmax commented on .vitepress/navigation.config.ts
> +        classes: 'bg-gradient-gold hocus:bg-gradient-gold-darkened',
- Migration: gold
- Build: blue
- Learn: green
- Validators: gold

As you can see validators and migration uses the same color.

Here are some alternative I can think of (trying to match the color with the section):

## Option 1

- Migration: **orange**
- Build: blue
- Learn: **gold**
- Validators: **green**

## Option 2

- Migration: **red**
- Build: blue
- Learn: green
- Validators: gold


**I like more option 1**

2025-01-07 04:21 UTC, onmax commented on validators/staking-faq.md
> +### General Staking Information
```suggestion
## General Staking Information
```

2025-01-07 04:21 UTC, onmax commented on validators/staking-faq.md
> +**What is Staking?**
```suggestion
### What is Staking?
```

If we use h3 for questions I think they will appear in the search and in google

2025-01-07 04:21 UTC, onmax commented on validators/staking-faq.md
> +**What is Staking?**
If you think the styles for h3 are too big we can always add a custom `<style>` in the page to reduce the font-size for h3

2025-01-07 04:21 UTC, onmax commented on validators/staking-faq.md
> +### General Staking Information
same for the rest of `###` in this page

2025-01-07 04:21 UTC, onmax commented on validators/staking-handbook.md
> +#### **Links and References**
```suggestion
### **Links and References**
```

2025-01-07 04:21 UTC, onmax commented on validators/staking-handbook.md
> +Failure to comply with this will result in immediate actions, including potential suspension or removal from the network.
Can we remove someone from the network? We can remove their information but not their validator, right?

2025-01-08 10:49 UTC, ines-toupeira commented on .vitepress/navigation.config.ts
> +        classes: 'bg-gradient-gold hocus:bg-gradient-gold-darkened',
the migration section will be archived soon, but I like option 1 as well. I'll change it

2025-01-08 11:00 UTC, ines-toupeira commented on validators/staking-faq.md
> +**What is Staking?**
I changed it. It looks a tad weird the sizing, but I'm not opposed to it

2025-01-08 11:04 UTC, ines-toupeira commented on validators/staking-handbook.md
> +Failure to comply with this will result in immediate actions, including potential suspension or removal from the network.
I'm waiting for an answer for this and then I'll make any necessary changes

2025-01-08 14:47 UTC, ines-toupeira commented on validators/staking-handbook.md
> +Failure to comply with this will result in immediate actions, including potential suspension or removal from the network.
removal from the wallet!

2025-01-09 11:27 UTC, onmax approved these changes

2025-01-09 11:27 UTC, merged